# Generated by Django 4.2.3 on 2023-09-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreatemodel',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/course'),
        ),
    ]
