# Generated by Django 4.2.3 on 2023-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coursecreatemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreatemodel',
            name='images',
            field=models.ImageField(upload_to='images/course'),
        ),
    ]
