# Generated by Django 4.2.3 on 2023-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_coursecreatemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreatemodel',
            name='slug',
            field=models.SlugField(choices=[('Quality Assurance', 'Quality Assurance'), ('Technology and IT', 'Technology and IT'), ('Research and Development', 'Research and Development')], max_length=40),
        ),
    ]
