# Generated by Django 4.2.3 on 2023-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_coursecreatemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreatemodel',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
