# Generated by Django 4.2.3 on 2023-09-02 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_coursecreatemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreatemodel',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
