# Generated by Django 4.2.3 on 2023-09-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_coursecreatemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreatemodel',
            name='slug',
        ),
    ]
